export const COM_STATUS = 'COM_STATUS'
// 用户模块
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_INFO_STORE = 'USER_INFO_STORE'
export const USER_SET_UID = 'USER_SET_UID'
export const USER_CLEAR_STORE = 'USER_CLEAR_STORE'
export const USER_SET_USERLIST = 'USER_SET_USERLIST'
export const USER_SET_CURENTPAGE = 'USER_SET_CURENTPAGE'
export const USER_SET_USER_ITEM = 'USER_SET_USER_ITEM'

// 服务模块
export const CATEGORY_SET_CATEGORYLIST = 'CATEGORY_SET_CATEGORYLIST'
export const CATEGORY_SET_CURENTPAGE = 'CATEGORY_SET_CURENTPAGE'
export const CATEGORY_SET_CATEGORY_ITEM = 'CATEGORY_SET_CATEGORY_ITEM'

// 服务模块
export const FOOD_SET_FOODLIST = 'FOOD_SET_FOODLIST'
export const FOOD_SET_CURENTPAGE = 'FOOD_SET_CURENTPAGE'
export const FOOD_SET_FOOD_ITEM = 'FOOD_SET_FOOD_ITEM'

// 订单模块
export const ORDER_SET_ORDERSLIST = 'ORDER_SET_ORDERSLIST'
export const ORDER_SET_CURENTPAGE = 'ORDER_SET_CURENTPAGE'
export const ORDER_SET_ORDER_ITEM = 'ORDER_SET_ORDER_ITEM'

// banner模块
export const BANNER_SET_BANNERLIST = 'BANNER_SET_BANNERLIST'
export const BANNER_SET_CURENTPAGE = 'BANNER_SET_CURENTPAGE'
export const BANNER_SET_BANNER_ITEM = 'BANNER_SET_BANNER_ITEM'

// desk模块
export const DESK_SET_DESKLIST = 'DESK_SET_DESKLIST'
export const DESK_SET_CURENTPAGE = 'DESK_SET_CURENTPAGE'
export const DESK_SET_DESK_ITEM = 'DESK_SET_DESK_ITEM'

// home模块
export const HOME_SET_DETAIL = 'HOME_SET_DETAIL'
export const HOME_SET_TODOLIST = 'HOME_SET_TODOLIST'
export const HOME_ADD_TODOLIST = 'HOME_ADD_TODOLIST'
export const HOME_EDIT_TODOLIST = 'HOME_EDIT_TODOLIST'
export const HOME_DELETE_TODOLIST = 'HOME_DELETE_TODOLIST'
export const HOME_CHECKCHANGE_TODOLIST = 'HOME_CHECKCHANGE_TODOLIST'

// setting模块
export const SETTING_SET_SETTINGLIST = 'SETTING_SET_SETTINGLIST'
export const SETTING_SET_WX_SETTING = 'SETTING_SET_WX_SETTING'
export const SETTING_SET_CURENTPAGE = 'SETTING_SET_CURENTPAGE'
export const SETTING_SET_SETTING_ITEM = 'SETTING_SET_SETTING_ITEM'
